services:
  app:
    image: workshop-laravel-api:latest
    container_name: workshop-api
    restart: unless-stopped
    working_dir: /var/www
    environment:
      APP_ENV: production # alterar
      APP_DEBUG: false
      APP_URL: https://sua-api.com # alterar
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: workshop_erp
      DB_USERNAME: username # alterar
      DB_PASSWORD: userpass # alterar
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: workshop-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: workshop-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: workshop_erp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: userpass # alterar
      MYSQL_USER: username # alterar
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: workshop-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data:
