services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: workshop-laravel-api
        container_name: workshop-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - redis
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: workshop-nginx
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: workshop-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-workshop_development}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        # volumes:
        #     - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: workshop-phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
        depends_on:
            - db
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: workshop-redis
        restart: unless-stopped
        ports:
        - "6379:6379"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
